# Dallas Crime Data

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import plotly as ply
import pandas_profiling as ppf

In [2]:
pwd

'C:\\Users\\Mike\\Google Drive\\Code\\Springboard\\Springboard\\capstones\\Dallas Open Data - New Crime Watch'

In [3]:
raw_crime = pd.read_csv("C:\\Users\\Mike\\Google Drive\\Code\\Springboard\\Springboard\\capstones\\Dallas Open Data - New Crime Watch\\Public Crime Data - 2014 to present - New_Crime_Watch.csv",
                       dtype={'Victim Business Phone':str,
                              'Special Report (Pre-RMS)':str,
                              'Victim Zip Code':str})
# raw_crime = pd.read_csv("C:\\Users\\Mike\\Google Drive\\Code\\Springboard\\Springboard\\capstones\\Dallas Open Data - New Crime Watch\\Public Crime Data - 2014 to present - New_Crime_Watch.csv",
#                         dtype={'X Coordinate': str,
#                               'Y Cordinate': str,
#                           },
#                         infer_datetime_format=True,
#                         low_memory=False)

In [4]:
raw_crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750862 entries, 0 to 750861
Data columns (total 92 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   Incident Address                           747686 non-null  object
 1   Zip Code                                   747347 non-null  float64
 2   Type of Incident                           750862 non-null  object
 3   Modus Operandi (MO)                        700360 non-null  object
 4   Victim Condition                           23207 non-null   object
 5   Victim Injury Description                  33473 non-null   object
 6   Victim Gender                              470593 non-null  object
 7   Person Involvement Type                    723225 non-null  object
 8   Incident Number w/year                     750862 non-null  object
 9   Year of Incident                           750862 non-null  int64
 10  Service Number ID                          750862 non-null  object
 11  Watch                                      750862 non-null  int64
 12  Call (911) Problem                         722787 non-null  object
 13  Type  Location                             749663 non-null  object
 14  Type of Property                           170434 non-null  object
 15  Victim Type                                715094 non-null  object
 16  Apartment Number                           163727 non-null  object
 17  Victim Race                                473743 non-null  object
 18  Reporting Area                             732223 non-null  float64
 19  Victim Home Address                        706352 non-null  object
 20  Beat                                       750546 non-null  float64
 21  Victim Apartment                           205192 non-null  object
 22  Division                                   750546 non-null  object
 23  Sector                                     750058 non-null  float64
 24  Victim City                                705750 non-null  object
 25  Council District                           477648 non-null  object
 26  Victim State                               700558 non-null  object
 27  Target Area Action Grids                   239510 non-null  object
 28  Victim Business Name                       36681 non-null   object
 29  Community                                  80303 non-null   object
 30  Victim Business Address                    26446 non-null   object
 31  Victim Business Phone                      10510 non-null   object
 32  Year1 of Occurrence                        750862 non-null  int64
 33  Month1 of Occurence                        750862 non-null  object
 34  Responding Officer #1  Badge No            720676 non-null  object
 35  Day1 of the Week                           750862 non-null  object
 36  Responding Officer #1  Name                719852 non-null  object
 37  Time1 of Occurrence                        750862 non-null  object
 38  Responding Officer #2 Badge No             271724 non-null  object
 39  Day1 of the Year                           750862 non-null  int64
 40  Responding Officer #2  Name                271723 non-null  object
 41  Reporting Officer Badge No                 722736 non-null  object
 42  Year2 of Occurrence                        750861 non-null  float64
 43  Assisting Officer Badge No                 556644 non-null  object
 44  Month2 of Occurence                        750861 non-null  object
 45  Reviewing Officer Badge No                 748087 non-null  object
 46  Day2 of the Week                           750861 non-null  object
 47  Element Number Assigned                    721677 non-null  object
 48  Time2 of Occurrence                        750861 non-null  object
 49  Investigating Unit 1                       544270 non-null  object
 50  Day2 of the Year                           750861 non-null  float64
 51  Investigating Unit 2                       544281 non-null  object
 52  Offense Status                             740902 non-null  object
 53  UCR Disposition                            740958 non-null  object
 54  Offense Entered Year                       750862 non-null  int64
 55  Family Offense                             723483 non-null  object
 56  Offense Entered Month                      750862 non-null  object
 57  Hate Crime                                 817 non-null     object
 58  Offense Entered Day of the Week            750862 non-null  object
 59  Hate Crime Description                     749636 non-null  object
 60  Offense Entered Time                       750862 non-null  object
 61  Weapon Used                                397379 non-null  object
 62  Offense Entered  Date/Time                 750862 non-null  int64
 63  Gang Related Offense                       426606 non-null  object
 64  Victim Package                             0 non-null       float64
 65  CFS Number                                 722788 non-null  object
 66  Drug Related Istevencident                 723470 non-null  object
 67  RMS Code                                   750862 non-null  object
 68  Criminal Justice Information Service Code  750862 non-null  int64
 69  Penal Code                                 750862 non-null  object
 70  UCR Offense Name                           395275 non-null  object
 71  Special Report (Pre-RMS)                   437 non-null     object
 72  UCR Offense Description                    395275 non-null  object
 73   UCR Code                                  395275 non-null  float64
 74  Victim Name                                720000 non-null  object
 75  Offense Type                               395275 non-null  object
 76  NIBRS Crime                                501063 non-null  object
 77  NIBRS Crime Category                       501063 non-null  object
 78  Victim Ethnicity                           473095 non-null  object
 79  NIBRS Crime Against                        501063 non-null  object
 80  Victim Age                                 438237 non-null  float64
 81  NIBRS Code                                 501063 non-null  object
 82  Victim Age at Offense                      418941 non-null  float64
 83  NIBRS Group                                501063 non-null  object
 84  NIBRS Type                                 501063 non-null  object
 85  Victim Zip Code                            698664 non-null  object
 86  X Coordinate                               731207 non-null  float64
 87  Y Cordinate                                731207 non-null  float64
 88  City                                       745928 non-null  object
 89  State                                      741891 non-null  object
 90  Location1                                  747686 non-null  object
 91  Update Date                                750862 non-null  object
dtypes: float64(12), int64(7), object(73)
memory usage: 527.0+ MB

In [5]:
raw_crime.iloc[0]

Incident Address                                      7740 MCCALLUM BLVD
Zip Code                                                         75252.0
Type of Incident            UNAUTHORIZED USE OF MOTOR VEH - TRUCK OR BUS
Modus Operandi (MO)      SUSPECT TOOK COMP'S VEHICLE WITHOUT PERMISSION.
Victim Condition                                                     NaN
                                             ...
Y Cordinate                                               7046427.235888
City                                                              DALLAS
State                                                                 TX
Location1              7740 MCCALLUM BLVD\nDALLAS, TX 75252\n(32.9878...
Update Date                                  2020-12-09 11:18:34.0000000
Name: 0, Length: 92, dtype: object

In [6]:
raw_crime['Update Date'] = pd.to_datetime(raw_crime['Update Date'])

In [7]:
raw_crime.head(2)

,Incident Address,Zip Code,Type of Incident,Modus Operandi (MO),Victim Condition,Victim Injury Description,Victim Gender,Person Involvement Type,Incident Number w/year,Year of Incident,...,Victim Age at Offense,NIBRS Group,NIBRS Type,Victim Zip Code,X Coordinate,Y Cordinate,City,State,Location1,Update Date
0,7740 MCCALLUM BLVD,75252.0,UNAUTHORIZED USE OF MOTOR VEH - TRUCK OR BUS,SUSPECT TOOK COMP'S VEHICLE WITHOUT PERMISSION.,NaN,NaN,NaN,NaN,069444-2020,2020,...,NaN,A,Coded,NaN,2.497997e+06,7.046427e+06,DALLAS,TX,"7740 MCCALLUM BLVD\nDALLAS, TX 75252\n(32.9878...",2020-12-09 11:18:34
1,3083 HERSCHEL AVE,75219.0,PUBLIC INTOXICATION,AP NATHALIE MONTERO WAS IN PUBLIC AND INTOXICATED,NaN,NaN,NaN,Victim,003862-2021,2021,...,NaN,B,90Z - No Coded,75220,2.485524e+06,6.983523e+06,DALLAS,TX,"3083 HERSCHEL AVE\nDALLAS, TX 75219\n(32.81452...",2021-01-07 06:11:11

In [8]:
raw_crime['X Coordinate']

0         2.497997e+06
1         2.485524e+06
2         2.523380e+06
3         2.494608e+06
4         2.460356e+06
              ...
750857    2.504783e+06
750858    2.491653e+06
750859    2.504766e+06
750860    2.482083e+06
750861    2.465562e+06
Name: X Coordinate, Length: 750862, dtype: float64

In [9]:
raw_crime.describe()

,Zip Code,Year of Incident,Watch,Reporting Area,Beat,Sector,Year1 of Occurrence,Day1 of the Year,Year2 of Occurrence,Day2 of the Year,Offense Entered Year,Offense Entered Date/Time,Victim Package,Criminal Justice Information Service Code,UCR Code,Victim Age,Victim Age at Offense,X Coordinate,Y Cordinate
count,747347.000000,750862.000000,750862.000000,732223.000000,750546.000000,750058.000000,750862.000000,750862.000000,750861.000000,750861.000000,750862.000000,750862.000000,0.0,7.508620e+05,395275.000000,438237.000000,418941.000000,7.312070e+05,7.312070e+05
mean,75224.258624,2017.551464,1.934024,3142.572428,415.978257,411.861789,2017.532363,187.996559,2017.544435,187.934873,2017.551513,187.734549,NaN,5.048104e+07,1408.482338,40.101680,39.921688,2.494417e+06,6.978244e+06
std,196.513305,1.986634,0.838296,1824.635377,196.787268,197.011197,2.039587,105.080468,1.984431,105.097825,1.982893,105.145164,NaN,3.531589e+07,1230.784064,15.274712,15.316257,2.197327e+04,3.130607e+04
min,0.000000,2005.000000,1.000000,1001.000000,3.000000,0.000000,1900.000000,1.000000,1984.000000,1.000000,2014.000000,1.000000,NaN,9.990017e+06,110.000000,-9.000000,0.000000,2.411659e+06,6.889043e+06
25%,75214.000000,2016.000000,1.000000,1247.000000,238.000000,230.000000,2016.000000,98.000000,2016.000000,98.000000,2016.000000,98.000000,NaN,2.299000e+07,630.000000,28.000000,28.000000,2.478421e+06,6.954975e+06
50%,75224.000000,2018.000000,2.000000,3059.000000,421.000000,420.000000,2018.000000,193.000000,2018.000000,194.000000,2018.000000,193.000000,NaN,2.999000e+07,710.000000,37.000000,37.000000,2.493141e+06,6.975776e+06
75%,75236.000000,2019.000000,3.000000,4321.000000,553.000000,550.000000,2019.000000,277.000000,2019.000000,277.000000,2019.000000,277.000000,NaN,1.000000e+08,2000.000000,50.000000,50.000000,2.506987e+06,7.001639e+06
max,98004.000000,2121.000000,3.000000,9611.000000,757.000000,750.000000,2021.000000,366.000000,2021.000000,366.000000,2021.000000,366.000000,NaN,1.000000e+08,5700.000000,934.000000,934.000000,2.593936e+06,7.088137e+06

In [10]:
raw_crime_report = ppf.ProfileReport(raw_crime, title='Dallas Crime',dark_mode=True,explorative=True)

In [11]:
raw_crime_report.to_file("RawCrime.html")

Summarize dataset:   0%|          | 0/106 [00:00<?, ?it/s]

C:\Users\Mike\.conda\envs\cap1\lib\site-packages\scipy\stats\stats.py:4594: RuntimeWarning: overflow encountered in longlong_scalars
  (2 * xtie * ytie) / m + x0 * y0 / (9 * m * (size - 2)))

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]